export type ConfirmationPolicyMode = "native" | "checking" | "preview";
export type ConfirmationTone = "ready" | "blocked" | "pending";

export type ConfirmationPolicyDecision = {
  category: string;
  policy: string;
  reviewer_required: string;
  human_confirmation: string;
  reason: string;
  allowed_now: boolean;
  requires_confirmation: boolean;
  requires_reviewer: boolean;
  requires_clear_task: boolean;
  requires_gate?: boolean;
};

export type ConfirmationPolicyRequirementView = {
  label: "Human confirmation" | "Reviewer" | "Clear task";
  status: string;
  detail: string;
  tone: ConfirmationTone;
};

export type ConfirmationPolicyView = {
  mode: ConfirmationPolicyMode;
  sourceLabel: string;
  overallStatus: string;
  tone: ConfirmationTone;
  summary: string;
  category: string;
  policy: string;
  reason: string;
  requirements: ConfirmationPolicyRequirementView[];
  emptyActionCopy: string;
};

export type ConfirmationPolicyInput = {
  mode: ConfirmationPolicyMode;
  policy: ConfirmationPolicyDecision | null;
};

function formatPolicyValue(value: string) {
  return value.replace(/_/g, " ");
}

function requirementStatus(required: boolean) {
  return required ? "Required" : "Not required";
}

function requirementTone(required: boolean): ConfirmationTone {
  return required ? "blocked" : "ready";
}

function buildNativeRequirements(policy: ConfirmationPolicyDecision): ConfirmationPolicyRequirementView[] {
  return [
    {
      label: "Human confirmation",
      status: requirementStatus(policy.requires_confirmation),
      detail: formatPolicyValue(policy.human_confirmation),
      tone: requirementTone(policy.requires_confirmation),
    },
    {
      label: "Reviewer",
      status: requirementStatus(policy.requires_reviewer),
      detail: formatPolicyValue(policy.reviewer_required),
      tone: requirementTone(policy.requires_reviewer),
    },
    {
      label: "Clear task",
      status: requirementStatus(policy.requires_clear_task),
      detail: policy.requires_clear_task ? "explicit task scope required" : "not required by sample policy",
      tone: requirementTone(policy.requires_clear_task),
    },
  ];
}

function nativeOverallStatus(policy: ConfirmationPolicyDecision) {
  if (policy.requires_reviewer) {
    return "Review required";
  }
  if (policy.requires_clear_task) {
    return "Clear task required";
  }
  if (policy.requires_confirmation) {
    return "Confirmation required";
  }
  if (policy.allowed_now) {
    return "Allowed now";
  }
  return "Blocked by policy";
}

function nativeTone(policy: ConfirmationPolicyDecision): ConfirmationTone {
  return policy.allowed_now && !policy.requires_confirmation && !policy.requires_reviewer && !policy.requires_clear_task
    ? "ready"
    : "blocked";
}

function nonNativeView(mode: Exclude<ConfirmationPolicyMode, "native">): ConfirmationPolicyView {
  const checking = mode === "checking";
  const sourceLabel = checking ? "Checking native sample policy" : "Browser preview policy unavailable";
  const status = checking ? "Checking native policy" : "Native-only policy unavailable";
  const unavailable = checking ? "Native-only (checking)" : "Native-only outside Tauri";

  return {
    mode,
    sourceLabel,
    overallStatus: status,
    tone: "pending",
    summary: checking
      ? "Waiting for get_foundation_status. Confirmation and reviewer policy data are native-only and are not fabricated while loading."
      : "Running outside the native app. Confirmation, reviewer, clear-task, and allowed-now policy decisions are unavailable outside Tauri.",
    category: unavailable,
    policy: unavailable,
    reason: checking ? "Checking native sample policy reason" : "Policy reason unavailable outside Tauri",
    requirements: [
      { label: "Human confirmation", status: unavailable, detail: unavailable, tone: "pending" },
      { label: "Reviewer", status: unavailable, detail: unavailable, tone: "pending" },
      { label: "Clear task", status: unavailable, detail: unavailable, tone: "pending" },
    ],
    emptyActionCopy: "Read-only preview only. This primitive displays requirements without creating identifiers, execution buttons, or runnable action state.",
  };
}

export function buildConfirmationPolicyView(input: ConfirmationPolicyInput): ConfirmationPolicyView {
  if (!input.policy) {
    return nonNativeView(input.mode === "native" ? "checking" : input.mode);
  }

  const { policy } = input;
  const overallStatus = nativeOverallStatus(policy);

  return {
    mode: "native",
    sourceLabel: "Native sample policy",
    overallStatus,
    tone: nativeTone(policy),
    summary: `Read-only rendering of the native sample policy. ${overallStatus}; no approval, confirmation ID, or execution state is generated by this UI.`,
    category: policy.category,
    policy: formatPolicyValue(policy.policy),
    reason: policy.reason,
    requirements: buildNativeRequirements(policy),
    emptyActionCopy: "Read-only preview of confirmation requirements. This primitive displays requirements without creating identifiers or runnable action state.",
  };
}
